name: Deploy Docker Container Image
permissions:
  packages: write
on:
  push:
    branches:
      - "main"
jobs:
  deploy_container:
    runs-on: ubuntu-latest
    environment: container-registry
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag ghcr.io/yoshida-ryuhei/alpine-gh-cli:latest
      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Register to GitHub Container Registry
        run: docker push ghcr.io/yoshida-ryuhei/alpine-gh-cli:latest
